services:
  - type: web
    name: flood-automation
    env: node
    buildCommand: |
      npm install
      npm run build
      npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
